codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 50%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "test/"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.config.ts"
  - "app/entry.*.ts"
  - "app/root.tsx"
  - "app/tailwind.css"
  - "docs/"
  - "*.md"