[phases.setup]
nixpkgs = ['nodejs-20_x', 'npm-10_x']

[phases.install]
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['npm run railway-build']

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'