[phases.setup]
nixpkgs = ['nodejs-20_x', 'npm-10_x', 'openssl']

[phases.install]  
cmds = ['npm ci --include=dev']

[phases.build]
cmds = [
  'npm run railway-build',
  'ls -la build/ || echo "Build directory check"'
]

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'