# Railway Nixpacks configuration for optimal Node.js deployment
[providers]
node = "22"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
CI = "false"
NODE_NO_WARNINGS = "1"

[phases.build]
cmds = [
    "npm ci --no-audit --no-fund",
    "npx prisma generate --no-hints",
    "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && node server.js"