services:
  - type: web
    name: wishcraft
    runtime: node
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: wishcraft-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: wishcraft-db
    plan: standard
    postgresMajorVersion: 15