client_id = "${SHOPIFY_API_KEY}"
name = "wishcraft"
handle = "wishcraft"
application_url = "${SHOPIFY_APP_URL}"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2024-10"

[access_scopes]
scopes = "read_customers,read_products,read_orders,write_orders,read_inventory"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "${SHOPIFY_APP_URL}/auth/callback",
  "${SHOPIFY_APP_URL}/auth/shopify/callback"
]

[pos]
embedded = false
