# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# SECURITY: Set via environment variable - DO NOT hardcode
# client_id = "YOUR_NEW_SHOPIFY_API_KEY"
name = "wishcraft"
handle = "wishcraft"
application_url = "https://wishcraft-production.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2024-10"

# [app_proxy]
# url = "https://wishcraft-production.up.railway.app/proxy" 
# subpath = "apps"
# prefix = "wishcraft"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Required scopes for WishCraft gift registry functionality (2025 compliant)
scopes = "read_customers,write_customers,read_products,read_orders,write_orders,read_inventory,write_content"

# Optional scopes for future features
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://wishcraft-production.up.railway.app/auth/callback",
  "https://wishcraft-production.up.railway.app/auth/shopify/callback"
]

[pos]
embedded = false
