export const SHOPIFY_CONFIG = {
  API_VERSION: "2025-07",
  API_TIMEOUT: 30000,
  
  VALIDATION: {
    REGISTRY_TITLE_MAX: 100,
    REGISTRY_DESCRIPTION_MAX: 2000,
    MAX_ITEMS_PER_REGISTRY: 250,
    MAX_COLLABORATORS: 50,
    MAX_MESSAGE_LENGTH: 1000,
    MIN_PASSWORD_LENGTH: 8,
  },
  
  SECURITY: {
    SESSION_COOKIE_NAME: "__session",
    SALT_ROUNDS: 10,
    TOKEN_EXPIRY: 24 * 60 * 60 * 1000,
    MIN_SECRET_LENGTH: 32,
  },
} as const;

export type ShopifyConfig = typeof SHOPIFY_CONFIG;