# Railway deployment configuration for WishCraft
[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
watchPatterns = ["**/package.json"]

[env]
NODE_ENV = "production"
PORT = { default = "3000" }

# Health check configuration
[healthcheck]
path = "/health"
intervalSeconds = 30
timeoutSeconds = 10
retries = 3

# Resource limits
[resources]
memory = 2048
cpu = 2000

# Scaling configuration
[scaling]
minReplicas = 2
maxReplicas = 10
targetCPU = 80
targetMemory = 85

# Networking
[networking]
allowedIPs = []
denylist = []