# Cloudflare Worker Configuration for WishCraft
# Edge computing setup for improved performance and global distribution

name = "wishcraft-edge-worker"
main = "cloudflare-worker.js"
compatibility_date = "2025-01-01"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Worker configuration
[build]
command = "npm run build:edge"

# Environment variables for different environments
[env.production]
name = "wishcraft-edge-worker-prod"
route = "https://wishcraft.app/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"

[env.production.vars]
ENVIRONMENT = "production"
SHOPIFY_APP_URL = "https://wishcraft.app"
ALLOWED_ORIGINS = "https://admin.shopify.com,https://*.myshopify.com"
CACHE_TTL = "300"

[env.staging]
name = "wishcraft-edge-worker-staging"
route = "https://staging.wishcraft.app/*"

[env.staging.vars]
ENVIRONMENT = "staging"
SHOPIFY_APP_URL = "https://staging.wishcraft.app"
ALLOWED_ORIGINS = "https://admin.shopify.com,https://*.myshopify.com,http://localhost:3000"
CACHE_TTL = "60"

# KV namespaces for edge storage
[[kv_namespaces]]
binding = "CACHE_KV"
id = "${CLOUDFLARE_KV_CACHE_ID}"
preview_id = "${CLOUDFLARE_KV_CACHE_PREVIEW_ID}"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "${CLOUDFLARE_KV_RATE_LIMIT_ID}"
preview_id = "${CLOUDFLARE_KV_RATE_LIMIT_PREVIEW_ID}"

# Durable Objects for stateful edge computing
[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionManager"

[[durable_objects.bindings]]
name = "ANALYTICS"
class_name = "AnalyticsCollector"

# R2 object storage for edge assets
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "wishcraft-edge-assets"

# Analytics and monitoring
[observability]
enabled = true

# Worker limits and configuration
[limits]
cpu_ms = 50
memory_mb = 128

# Custom domains
[[routes]]
pattern = "wishcraft.app/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"

[[routes]]
pattern = "*.wishcraft.app/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"